version: '3.2'

services:
  text_classifier:
    image: text_classifier
    build: .
    ports:
        - "8501:8501"
    volumes: 
      - type: bind
        source: ${HOME}/Downloads/content/text_classifier # this is the folder that contains the model/s and model versions
        target: /models/text_classifier   
      - type: bind
        source: ./model.config
        target: /models/model.config
        read_only: true   